"""create risk assessments table

Revision ID: 213b8cb2a548
Revises: 3c6874e44efa
Create Date: 2026-06-16 16:25:31.058658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213b8cb2a548'
down_revision: Union[str, Sequence[str], None] = '3c6874e44efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.Column('risk_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_assessment_date'), 'risk_assessments', ['assessment_date'], unique=False)
    op.create_index(op.f('ix_risk_assessments_district_id'), 'risk_assessments', ['district_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessments_district_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_assessment_date'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    # ### end Alembic commands ###
