"""add aqi and heat index

Revision ID: 36d70ad1d9d6
Revises: 79810213d5b8
Create Date: 2026-06-18 06:52:15.712909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d70ad1d9d6'
down_revision: Union[str, Sequence[str], None] = '79810213d5b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('climate_observations', sa.Column('aqi', sa.Integer(), nullable=True))
    op.add_column('climate_observations', sa.Column('heat_index_c', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('climate_observations', 'heat_index_c')
    op.drop_column('climate_observations', 'aqi')
    # ### end Alembic commands ###
