"""create climate health indices table

Revision ID: 3c6874e44efa
Revises: 5ddc11140986
Create Date: 2026-06-16 16:21:05.486333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c6874e44efa'
down_revision: Union[str, Sequence[str], None] = '5ddc11140986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climate_health_indices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('calculation_date', sa.Date(), nullable=False),
    sa.Column('chi_score', sa.Float(), nullable=False),
    sa.Column('health_status', sa.String(length=30), nullable=False),
    sa.Column('calculation_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_climate_health_indices_calculation_date'), 'climate_health_indices', ['calculation_date'], unique=False)
    op.create_index(op.f('ix_climate_health_indices_district_id'), 'climate_health_indices', ['district_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_climate_health_indices_district_id'), table_name='climate_health_indices')
    op.drop_index(op.f('ix_climate_health_indices_calculation_date'), table_name='climate_health_indices')
    op.drop_table('climate_health_indices')
    # ### end Alembic commands ###
