"""add population and area to districts

Revision ID: 79810213d5b8
Revises: 213b8cb2a548
Create Date: 2026-06-17 22:33:44.225831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79810213d5b8'
down_revision: Union[str, Sequence[str], None] = '213b8cb2a548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('districts', sa.Column('population', sa.Integer(), nullable=True))
    op.add_column('districts', sa.Column('area_km2', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('districts', 'area_km2')
    op.drop_column('districts', 'population')
    # ### end Alembic commands ###
