"""create climate observations table

Revision ID: 853a947d291c
Revises: 7f148991a328
Create Date: 2026-06-16 14:40:34.647265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '853a947d291c'
down_revision: Union[str, Sequence[str], None] = '7f148991a328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climate_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=False),
    sa.Column('humidity_percent', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_climate_observations_district_id'), 'climate_observations', ['district_id'], unique=False)
    op.create_index(op.f('ix_climate_observations_observation_date'), 'climate_observations', ['observation_date'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_climate_observations_observation_date'), table_name='climate_observations')
    op.drop_index(op.f('ix_climate_observations_district_id'), table_name='climate_observations')
    op.drop_table('climate_observations')
    # ### end Alembic commands ###
